/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Ex00_Rx72                              */
/*      FILE         :  Ex00_Rx72.c                            */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "iodefine.h"

int main(void) {
  PORT9.PDR.BIT.B5 = 1; // Set P95 as output
  PORT9.PDR.BIT.B6 = 1; // Set P96 as output
  PORT9.PODR.BIT.B5 = 0; // Set P95 low (LED off)
  PORT9.PODR.BIT.B6 = 0; // Set P96 low (LED off)

    while(1) {
      PORT9.PODR.BIT.B5 = 1; // Set P95 high (LED on)
      PORT9.PODR.BIT.B6 = 1; // Set P96 high (LED on)
      for (int i = 0; i < 10000; i++) {
        asm("nop");
      }
      PORT9.PODR.BIT.B5 = 0; // Set P95 low (LED off)
      PORT9.PODR.BIT.B6 = 0; // Set P96 low (LED off)
      for (int i = 0; i < 10000; i++) {
        asm("nop");
      }
    }
}